apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-api
  namespace: datadog
spec:
  encryptedData:
    api-key: AgAmCZo5ACJ7yALgTkMPw3g260ZXb+62/ES1iMEJyWpSh8x7E0fNPig30Oh8c3qcLXsu+nww/pG6psyml08Mt6f1vtcGLmEeEM+sJHvuUIsqaoTMFeTrgUcT2t+L3fvo4iaycaYXJt+mDAqEn7supEeAkva7fZXss+9xzf8xPAur8g8bSmhVCLAfs16JFVdTBTNBoWzA5EzPzBIo1fQ00HSfTfLsUuFrJsGroQCqe/o0UnvVHMSV8tHSb47hRSg2S8UDArHW1Ll79wRAS+kaaryF9wF2+9wgwG+AYWMHGvDXZuFqxkpCJIvOZflLGDmPDj0ILMA+atq3+l0wii22UVskt5Dn67mNh9PyUyXFGyzQ+muKXRoNx+tTYsf/ZRRAVxGd0/xlnTfQWb2dt3u8PqXoZ3MFDd+flx26rOTWfci84d6MQNg9fWOD67vkA4awur8SJuDLJp3zc9qbzadxCHBYQNdYB+iI1tTnTG6PeDJNMgMgu/rPlgCEpXMpBaEHyEb5/Bg+8x8Sbp2sPOQI1S02Sbrid+FxGWo41eq4srdy4zzYUP0Zj5JC/OM9ZJRFaxzag2uB7OG4roe7+UKj6oSp6AgzMxzIY8G9JnqfIioP0CEy39fTmmybTVdiUOL05fp2GT8WfAfjX3LbE3snoSWwnzljwsBvoNE2xsIFBjY96pLi+w8xxKT9zPC2G9ltaXAIJR/uRrz+Fp3Ni+6tYkN9pYB1Gf+OTIzL8fjbxFVO6A==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-api
      namespace: datadog

