traefik:
  metrics:
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        additionalLabels:
          release: "observability"
        honorLabels: true
        scrapeTimeout: 30s
        jobLabel: traefik
  tracing:
    jaeger:
      localAgentHostPort: observability-jaeger-agent.observability:6831
      propagation: jaeger
  deployment:
    replicas: 3
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                  - production
  globalArguments: []
  tlsStore:
    default:
      defaultCertificate:
        secretName: cloudflare-client-tls
  ingressRoute:
    dashboard:
      entryPoints:
        - websecure
      matchRule: Host(`traefik.farwydi.dev`)
  logs:
    general:
      level: DEBUG
  ports:
    web:
      expose: false
    websecure:
      http3:
        enabled: true
  additionalArguments:
    - "--serversTransport.rootCAs=/certs/cloudflare-origin-ca-ecc-root.crt"
  volumes:
    - name: cloudflare-origin-ca-ecc-root-cert
      mountPath: "/certs"
      type: secret
  service:
    annotations:
      kubernetes.digitalocean.com/load-balancer-id: "d6387c85-f945-409b-8eef-2ffbd1a2c9bb"
      service.beta.kubernetes.io/do-loadbalancer-name: "homelab-k8s-main-lb"
  tlsOptions:
    default:
      clientAuth:
        secretNames:
          - cloudflare-origin-pull-ca-cert
        clientAuthType: RequireAndVerifyClientCert
