traefik:
  tracing:
    datadog:
      localAgentHostPort: datadog.datadog.svc.cluster.local:8126
  metrics:
    datadog:
      address: datadog.datadog.svc.cluster.local:8125
  globalArguments: []
  tlsStore:
    default:
      defaultCertificate:
        secretName: cloudflare-client-tls
  ingressRoute:
    dashboard:
      entryPoints:
        - websecure
      matchRule: Host(`traefik.farwydi.dev`)
  logs:
    general:
      level: DEBUG
  ports:
    web:
      expose: false
    websecure:
      http3:
        enabled: true
  additionalArguments:
    - "--serversTransport.rootCAs=/certs/cloudflare-origin-ca-ecc-root.crt"
  volumes:
    - name: cloudflare-origin-ca-ecc-root-cert
      mountPath: "/certs"
      type: secret
