apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: primary-credentials-logs
  namespace: lgtm
spec:
  encryptedData:
    password: AgC7d0f+Z7XHp6DkqXUDCK1gDsLCsLJSIwsI34dIEZgbxZywiJEpgArvhvy+NUk7SQflVnPxoAeDqAZkNchuLzMIUGFI0zPq2Qvd9EPa/0ka0i24Fl2piroZdEQlmMFDeMjS1GO+p3mLJppCWIXFqS6cWQ8Bc5XrDRhGkkQ5CnTZbkF87oz0I6yZ8/UMnniUVm4D8rnT2ezMA3qYtgfb78IxEz5THYb+eNlIkhh4Z+nSni+eBu9dBTdsb3kWOSFiAHiky4aXTKMMuHnr14tvONbng9nU+fQO+VhCGLAamMr7qnJsR3xOkKa2/vjKKCRC0km3rrupVXOBCfPOJ9OP0tX3SrQaZ97KIA1EXtzo052brIj3kU5+5Wv4tAUHYFV8uAgwt4o1gcerBLlGbxjsupMI9/YMEJ0d/Dpmt2GUHziQ4BRxW4B+vyQ832e+rG27bkogvY5EIy3ygl6ZZz8E0iy8uN5vEWrOBvP1DMzToqcn8b9T5tEOeDk5Em1DXgQTidwU6rMmbu5GPeJJmrUUfdrT4HMeiW28BtvAy/imb8q2u5FmvzH2W5Slkizym+yGNl59vPYNK2MgN/QpBqwvlOdw6199LyP82IltEV6wo2duFqN7dJI2xM0o+iKUUbh3MEH+WYpEHsRKIVeIlPakJnst9PFnSzNiVHhhSw06+TZGSxxIbtoUKvxNNnYfPFhM3AE28n0k5LAXpULegBIcKfTHPpBXPXm17Gszh4O0cORFkh2qgMRA79Rv7/5iYXkxXaedfl1WY8t1gGb3CWsUnKPeS+WaXCBJS4RGNHyrPigysHEo5kulRE3dacHlfUzq1sIuAMU/
    username: AgCpxdddOgjFJZnRgkMyhYYadAh3dlYwttLj88MtBd5VNqof8TDm/93ZyAcZyelXJkrw4Zz2M6i5JeLFnDxrAYD0mWR2rDpPldPC+LLgKavxur52LMWIzfxCrX8nuXSlWA79Eicb96AU0so8mpHBJE1FRkb8NeH2fvuuOdpMhqbs/lDtj5c2n9juuFtRyPetPR8FtfP72EF95LxxhVdPF1Uvp0dYrlRrv9X8nfOvKUqx5Ktnf+yi8dTJrgcucfSB8DSjEJO4x7v3oZr5O0HdsFj15v9woDbb5T+rzJYVfhDhZdcU0h2MdFU0RQ0b7JPnU4XyOCEJP0uB6akUNwkVSnhMBDfxdlOiF8ncKCl6mGRAq7/egmN9G4q17oaAKBTBsFTwZqemblzmprWLlb6czP/Un0nzTgAl2Em9awF1ivk6jYdOwuVxgWp2nWW95b6bBYgbF57V+3gr1zWNHtbTXSbBeeFsX5bEQM6ogYnlNUzZSU1jnsKMInG/xaUUjPZwqIk996HOepGPx7rVa0np1XGjY3hv3WM7qggDV5qTpuACV2hBPQ8KWI3weBLsbKM4TrxvRi+oouu6ZSUlip92JvdKYN+v2yhnNZUPzMtjfzjxTynKHLWrDwybfR0n6v38mOZs8g3mUoW+Axn9U0VRe07KyxXtOUon/cs0WH7iNzIyLLGv+8OLqcP/DUWXv4xrCjc43BNS5/c=
  template:
    metadata:
      creationTimestamp: null
      name: primary-credentials-logs
      namespace: lgtm

