apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: all-pods
  namespace: lgtm
  labels:
    instance: primary
spec:
  pipelineStages:
    - docker: {}
  namespaceSelector:
    matchNames:
      - argocd
      - buildkite
      - default
      - kube-node-lease
      - kube-public
      - kube-system
      - lgtm
      - metrics-server
      - mplus
      - traefik
  selector:
    matchLabels: {}
