apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: buildkite-secrets
  labels:
    {{- include "buildkite.labels" . | nindent 4 }}
spec:
  encryptedData:
    private-ssh-key: AgCD5gZNn0W5IWJWqTBp8X7aaZEfpWcSVaH6UeWLzUttt0sYdAotA0dxeLoW83cL88C/mgseGMsfyZ4DXHEEuh8ul/j8oAfYPU8Cwqr5vhoulBzN4TIMVbpg9ZucmU29ZDd8KvWV0b5yzO2QlbXeVS/9SZCCp+N7ItYab77GSn9eGnErSu5+xILkjjZ3ir8koQhgIuEvWUoEKo3S9ChmRPn3cFbFA+L6Hh+azZdsLrTSsqopCCcjiuu9cKRcLmPI8k8Y48GRmU5eZUJhS2j1PiSsDS2dSZOoa27Z3wL21TI0OMnQVAA9STHOa/S1Xu8ghyZp6MJzQdrJprE+88J5kvc+hjBQUxH5AJkca4oHLwpc+xcn/Vnwfii6hP+MhByIF5Jy+eULwEGG7hHMTxO8ePnKGoNfsTjZfwcsQ8kigtkbKGEibOSsilAQSebKjK7sdcaeZxZiB4eqzul63Vc61SNY3KdB/tWJlQX3KUeP/OdDgD84cgWOR1HaHvTTGynxNGLZTjv/BKlHE53qB6vXRb70UwFzVtLU1Kc/JYJQMgW4xUXb0AbSaYLbt1P6OLa5xIFd5ZXpphA0+gclBe6LTborjSdtg4F64jqD3IhKWXw6LOPvBKzNbFh0znb175OVSNcD2ZlqKME3dHMYBVNRMTh4vAWpxpIbgI4uTV4Fm+nOZEhpTK1//d8EVL74/DE3mvsoYqbGH5WhOKsJpqhO04ar19fpCfK17VD5ZnTTIazaPCSblriir0pwihhy6JJ/HBS6Ops3caXwY4FPO7+M1E3H8YL5etBDiBlHN8E5KUX0zcKQCdkLJEXE1IKwdgEkydad1nXxoiXR55XFaQoVwC9nVVD3kWax6xdAVAK9wV+N/qcWaOqlxTKhJEwzFz1s+XPQXiItXZ4WQOUAfsnosGJtPKqE7ZBdGF3W+HgIl+/GJmAKS+K9+L7jUobOrH7/CIHr1wBPu8Kb2/iMKXKo7NYxFk7GHe9zfP6xLBnGvUg+oSyo+tgZqnFMvjdLlMcOoxkbzvSxy43swhAQzD58t/RfzBMeWQP2Fz6YUOKQYGi6e4QJBLbh/UEhgUe8lIL0PwTTNQn4Oz+zdFReGpJuJA21kUpXE+0NIoVo9WtQFUKVaB+A3bnt/a9Pgvrrj9prL37ew3Zq3e/N/qubof05DjiqUopaQqq57TjhaB7heMM9wzGukL0oSY7EzMbjtIc/KtZL8h/lu1m/J3Bw2a4Xm85mcZ0pmwN+7p7Mc+U=
  template:
    metadata:
      name: buildkite-secrets
      labels:
        {{- include "buildkite.labels" . | nindent 8 }}
