apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  labels:
    {{- include "buildkite.labels" . | nindent 4 }}
data:
  buildkite-agent.cfg: |
    build-path="/buildkite/builds"
    hooks-path="/buildkite/hooks"
    name="%hostname-%spawn"
    plugins-path="/buildkite/plugins"
    tags="queue=default"
    token="use-environment-variable"
